import type { Metadata } from "next";
import "./globals.css";
import MyHeader from "@/components/header/myheader";
import Footer from "@/components/footer";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "App Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MyHeader />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
