import type { Metadata } from "next";
import "./globals.css";
import MyHeader from "@/components/header/myheader";
import Footer from "@/components/footer";
import Providers from "../lib/providers";

export const metadata: Metadata = {
  title: "App Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="dark:bg-gray-900 bg-cases bg-no-repeat bg-gradient-to-b from-orange-500/5 dark:from-orange-800/10 dark:text-gray-400">
            <MyHeader />
            <main className="min-h-screen mx-auto max-w-7xl px-5 lg:px-8 pt-8">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
